[pytest]
pythonpath = .
testpaths = tests
#arquivo criado para que o test funcione. 
#Ele não estava considerando a raiz do projeto para procurar o app no módulo, com este arquivo ele consegue procurar na raiz também.